export class CompanyData {
  public static companies: any = [
    {
      id: "1",
      pic: './assets/media/users/default.jpg',
      name: "Roobee",
      info: "BlockChain, Investments",
      badge: true,
      isW: false,
      desc: "Roobee is an international financial technology company providing an AI-powered blockchain Roobee is an international financial technology company providing an AI-powered blockchain",
      status: "Inactive",
      started: "Apr 17, 2019",
      access: "Vlad, Michael",
    },
    {
      id: "2",
      pic: './assets/media/project-logos/1.png',
      name: "Airbnb",
      info: "Hospitality Services",
      badge: false,
      isW: true,
      desc: "A‌i‌r‌b‌n‌b‌,‌ ‌I‌n‌c‌.‌, is an American online marketplace and hospitality service brokerage company bas A‌i‌r‌b‌n‌b‌,‌ ‌I‌n‌c‌.‌, is an American online marketplace and hospitality service brokerage company bas",
      status: "Pending",
      started: "Apr 17, 2011",
      access: "Vlad",
    },
    {
      id: "3",
      pic: './assets/media/project-logos/4.png',
      name: "Roobee",
      info: "BlockChain, Investments",
      badge: true,
      isW: true,
      desc: "Roobee is an international financial technology company providing an AI-powered blockchain Roobee is an international financial technology company providing an AI-powered blockchain",
      status: "Inactive",
      started: "Apr 17, 2019",
      access: "Vlad, Michael",
    },
    {
      id: "4",
      pic: './assets/media/project-logos/2.png',
      name: "Airbnb",
      info: "Hospitality Services",
      badge: false,
      isW: false,
      desc: "A‌i‌r‌b‌n‌b‌,‌ ‌I‌n‌c‌.‌, is an American online marketplace and hospitality service brokerage company bas A‌i‌r‌b‌n‌b‌,‌ ‌I‌n‌c‌.‌, is an American online marketplace and hospitality service brokerage company bas",
      status: "Pending",
      started: "Apr 17, 2011",
      access: "Vlad",
    },
    {
      id: "5",
      pic: './assets/media/project-logos/5.png',
      name: "Roobee",
      info: "BlockChain, Investments",
      badge: true,
      isW: false,
      desc: "Roobee is an international financial technology company providing an AI-powered blockchain Roobee is an international financial technology company providing an AI-powered blockchain",
      status: "Inactive",
      started: "Apr 17, 2019",
      access: "Vlad, Michael",
    },
    {
      id: "6",
      pic: './assets/media/project-logos/3.png',
      name: "Airbnb",
      info: "Hospitality Services",
      badge: false,
      isW: true,
      desc: "A‌i‌r‌b‌n‌b‌,‌ ‌I‌n‌c‌.‌, is an American online marketplace and hospitality service brokerage company bas A‌i‌r‌b‌n‌b‌,‌ ‌I‌n‌c‌.‌, is an American online marketplace and hospitality service brokerage company bas",
      status: "Pending",
      started: "Apr 17, 2011",
      access: "Vlad",
    },
  ];
}
